### ISSUE TITLE
ovirt_vm should support HA

### ISSUE THREAD

**Issue by jake2184** [haveyoudebuggedit/terraform-provider-ovirt#42]
## Please describe what you would like to see

When creating a VM, I should be able to specify if the VM should be made HA, and which storage domain the lease should be in.

This is supported in the current provider.

```
resource "ovirt_vm" "myvm" {
  ...
  high_availability = true
  lease_domain = "myStorageDomain"
}
```

**Comment by janosdebugs** [comment]
Closing this issue as it has been transferred to the original repository.
